### ISSUE TITLE
Using Actual with existing DuckDNS domain

### ISSUE THREAD

**Issue by gschmidl** [sztupy/hassio-actualbudget#1]
I have a DuckDNS domain already set up to serve Home Assistant at port 443, with Let's Encrypt and nginx.

How can I integrate Actual to be accessed? Simply going to https://mydomain.duckdns.org:5006 gives an SSL error, and going to http:// is automatically forwarded to https://. Going to http://[my internal ip}:5006 does "work" but gives the warning that SharedArrayBuffer is disabled.

Thank you.

**Comment by sztupy** [comment]
You should create a subdomain like actualbudget.mydomain.duckdns.org and set that up based on the guide

**Comment by gschmidl** [comment]
Ok, I don't think that's going to work as ports 80 and 443 are taken by other services and the nginx can't start. If I remove those ports or change them, the add-on's npm doesn't seem to work.

**Comment by sztupy** [comment]
Ah I see. You likely need the ngunx proxy manager this addon uses to be on 443 and 80 and the other services that need those ports should be proxied using that. Alternatively I guess you can run the nginx proxy manager on a different port like 4433 and then you would connect to actual through that

**Comment by gschmidl** [comment]
I think I'll give it some more time as nginx seems to just have stopped using MariaDB, but hasn't yet removed the check from startup - so if I install both nginx and MariaDB, nginx starts up and uses SQLite instead, but if MariaDB isn't installed, nginx does not start up. That's not your extension's fault, though, so I'll close this - thanks for the tips!
