### ISSUE TITLE
Actual budget version / update

### ISSUE THREAD

**Issue by Zulex** [sztupy/hassio-actualbudget#4]
First of all, huge thanks for implementing this for Hassio, hugely appreciated!

I was wondering how updates from the root Actual Budget project are pushed to this repo? Is it a direct connection (and thus updates will be going directly from the root project), or are you updating manually?

Keep up the great work!

**Comment by sztupy** [comment]
There's a GitHub action set up to track updates automatically every 4 hours: https://github.com/sztupy/hassio-actualbudget/blob/main/.github/workflows/update-version.yml

This means any time there's a new commit or tag this project gets updated within the next couple hours.
