### ISSUE TITLE
Support on getting addon to work on homeassistant

### ISSUE THREAD

**Issue by joelstahre** [sztupy/hassio-actualbudget#9]
Hello, i have been following the steps to get the addon to work as expected.

**DuckDNS:**
addon installed and running
![Screenshot 2024-06-25 at 10 57 12](https://github.com/sztupy/hassio-actualbudget/assets/2317917/e03486ef-a18f-4a83-84df-e882cc70f88b)

![Screenshot 2024-06-25 at 10 58 18](https://github.com/sztupy/hassio-actualbudget/assets/2317917/afbb02f7-7407-4277-978b-c4b7958e3469)

**MariaDB**
addon installed and running

**Actual Budget**
addon installed and running
i can access it on http with the warning
![Screenshot 2024-06-25 at 11 01 26](https://github.com/sztupy/hassio-actualbudget/assets/2317917/9193816f-a1a8-4b7d-b7c0-7f3950eba0cd)

**Nginx Proxy Manager**
addon installed and running

Config
![Screenshot 2024-06-25 at 11 03 47](https://github.com/sztupy/hassio-actualbudget/assets/2317917/c72a11e9-ca55-4ac2-8574-04254d25cd30)
![Screenshot 2024-06-25 at 11 04 30](https://github.com/sztupy/hassio-actualbudget/assets/2317917/94c67aaa-bd7c-42cd-b496-97196a8a05a7)

443 is forwarded to homeassistant:8123 in my router

and i still get this: 
![Screenshot 2024-06-25 at 11 10 16](https://github.com/sztupy/hassio-actualbudget/assets/2317917/469eaf8f-6095-4f7b-9155-0224f02af39e)

Im not really sure what is wrong here.

the blured in the pics are a identifier i choose not to show, but in short:

i have a duckdns name personal-actual.duckdns.org
i created a wildcard certificate: *.personal-actual.duckdns.org
i created a proxyhost : stable.personal-actual.duckdns.org

**Comment by danielm-m** [comment]
Can you please tell us what the solution was? :)
